### ISSUE TITLE
Multithreaded extraction

### ISSUE THREAD

**Issue by AnyOldName3** [erri120/OMODFramework#28]
We discussed this a little in the past, but I can't remember what came of it. As extracting OMODs takes so long, it would be nice if more than one thread could be used. I've not checked whether OBMM used multiple threads during extraction.

If the format isn't amenable to this, I feel like it's probably better to have a written record of it that can be referred to in the future.

**Comment by erri120** [comment]
Done in 7980a6379f344c9c05fa92aca45742453c76b1f7 but still has some quirks.
